name: Debug build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build CDDA-iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: bundle install
      - name: Write certs deploy key
        run: |
          echo "${{ secrets.APPLE_CERTIFICATES_DEPLOY_KEY }}" > ~/.ssh/apple_certs_deploy
          chmod 0600 ~/.ssh/apple_certs_deploy
      - run: bundle exec fastlane match development --git_url=git@github.com:nornagon/apple-certificates --git_private_key=$HOME/.ssh/apple_certs_deploy
        env:
          FASTLANE_USER: nornagon+us@nornagon.net
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - run: bazelisk build //:cdda_ios
